module.exports = {
  MISSING_FIELD: 'MISSING_FIELD',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_DATE: 'INVALID_DATE',
  FIELD_NOT_ACCEPTED: 'FIELD_NOT_ACCEPTED',
  INVALID_SSN: 'INVALID_SSN',
  INVALID_CHARACTER: 'INVALID_CHARACTER',
  INSUFFICIENT_ARGUMENTS: 'INSUFFICIENT_ARGUMENTS',
};
